Vagrant.configure("2") do |config|
  config.vm.define "master" do |vm1|
    vm1.vm.hostname = "master"
    vm1.vm.box = "generic/centos8"
    vm1.vm.network "public_network" 
    vm1.vm.network "private_network", ip: "192.168.10.20"

    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ansible_master"
      vb.gui = false
      vb.memory = "2024"
    end

    vm1.vm.provision "shell", run: "once", inline: <<-SHELL
        echo "nameserver 1.1.1.1" > "/etc/resolv.conf"
        dnf update -y
        dnf install -y epel-release
        dnf install -y ansible
        echo "Ansible was sucessfully installed"
    SHELL
  end

  config.vm.define "slave" do |vm2|
    vm2.vm.hostname = "slave"
    vm2.vm.box = "generic/centos8"
    vm2.vm.network "public_network"
    vm2.vm.network "private_network", ip: "192.168.10.21"

	
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ansible_slave"
      vb.gui = false
      vb.memory = "1024"
    end

    vm2.vm.provision "shell", run: "once", inline: <<-SHELL
        echo "nameserver 1.1.1.1" > "/etc/resolv.conf"
        dnf update -y
    SHELL
  end
  
end