---
# Copying the latest dev/production code from the version control system.

- name: Delete index.html if exists
  file: path=/var/www/html/index.html state=absent

- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/ force=yes