---
# Playbook to perform common tasks on all the hosts.

- name: Enable Firewall on all the hosts
  service: name=firewalld state=started enabled=yes
    
- name: Enable the firewall port for SSH
  firewalld: port=22/tcp permanent=true state=enabled immediate=yes
    
- name: Allow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication yes"
              state=present
  notify: restart ssh